"""pseudonimo refactoring

Revision ID: 6ce38c918174
Revises: 6a8ef7ad819c
Create Date: 2025-07-02 02:05:38.407885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ce38c918174'
down_revision: Union[str, None] = '6a8ef7ad819c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pseudonimo', sa.Column('pseudonimo', sa.String(), nullable=False))
    op.add_column('pseudonimo', sa.Column('pseudonimo_norm', sa.String(), nullable=False))
    op.drop_constraint(op.f('uq_beneficiario_pseudonimo'), 'pseudonimo', type_='unique')
    op.create_unique_constraint('uq_beneficiario_pseudonimo', 'pseudonimo', ['beneficiario_id', 'pseudonimo_norm'])
    op.drop_column('pseudonimo', 'nombre_original')
    op.drop_column('pseudonimo', 'nombre_norm')
    op.drop_column('pseudonimo', 'nombre_limpio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pseudonimo', sa.Column('nombre_limpio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pseudonimo', sa.Column('nombre_norm', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pseudonimo', sa.Column('nombre_original', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_beneficiario_pseudonimo', 'pseudonimo', type_='unique')
    op.create_unique_constraint(op.f('uq_beneficiario_pseudonimo'), 'pseudonimo', ['beneficiario_id', 'nombre_norm'], postgresql_nulls_not_distinct=False)
    op.drop_column('pseudonimo', 'pseudonimo_norm')
    op.drop_column('pseudonimo', 'pseudonimo')
    # ### end Alembic commands ###
